name: CI

on:
  push:
    branches:
      - ci-cd

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.7

      - name: Install dependencies
        run: |
          cd eotdl
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root
      
      # - name: API tests
      #   run: poetry run pytest api/tests --cov .

      - name: lib tests
        run: poetry run pytest eotdl/tests --cov .

      - name: Check code with Pylint
        run: |
          poetry run pylint --fail-under=9 $(find . -type f -name "*.py" -not -path "./.venv/*")

      - name: Format code with Black
        run: |
          poetry run black --check --diff .

      - name: Install Flake8
        run: poetry run pip install flake8

      - name: Lint with Flake8
        run: |
          poetry run flake8 .