name: Test

on:
  push:
    branches:
      - ci-cd

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Install dependencies
        run: |
          cd eotdl
          poetry install --no-interaction --no-root
      
      - name: API tests
        run: poetry run pytest ../api --cov .

      - name: lib tests
        run: |
          cd eotdl
          poetry run pytest --cov .